services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "8082:8082"
      - "9092:9092"
    env_file:
      - common.env
    volumes:
      - db_data:/usr/src/db-backup

  web:
    build:
      context: ../../
      dockerfile: CA4/Part2/Dockerfile_web
    ports:
      - "8080:8080"
    env_file:
      - common.env

volumes:
  db_data: